/**
 * EVT_* 시그니처 상수/타입
 * Code Data System - Event 데이터 분류 키 (PlatformEventType과 동일 값 사용)
 *
 * 값은 PlatformEventType 문자열과 동일하게 유지 (별도 'EVT_' 접두사 없음)
 * 이벤트 로그 코드에서 이 상수를 사용하여 오타 방지
 */

export const EVT_SIGNATURES = {
  // 화물 관련
  CARGO_CREATED: 'CARGO_CREATED',
  CARGO_REMOVED: 'CARGO_REMOVED',
  CARGO_TAXONOMY_UPDATED: 'CARGO_TAXONOMY_UPDATED',
  // 규정 관련
  RULE_CHECKED: 'RULE_CHECKED',
  RULES_PASSED: 'RULES_PASSED',
  // 수요 세션 관련
  DEMAND_SESSION_CREATED: 'DEMAND_SESSION_CREATED',
  QUANTITY_SET: 'QUANTITY_SET',
  CUBE_CALCULATED: 'CUBE_CALCULATED',
  RESOURCE_READY: 'RESOURCE_READY',
  RESOURCE_CHECKED: 'RESOURCE_CHECKED',
  // 조건 설정 관련
  STORAGE_LOCATION_SET: 'STORAGE_LOCATION_SET',
  STORAGE_PERIOD_SET: 'STORAGE_PERIOD_SET',
  TRANSPORT_ORIGIN_SET: 'TRANSPORT_ORIGIN_SET',
  TRANSPORT_DESTINATION_SET: 'TRANSPORT_DESTINATION_SET',
  TRANSPORT_DATE_SET: 'TRANSPORT_DATE_SET',
  // 매칭 관련
  SEARCH_EXECUTED: 'SEARCH_EXECUTED',
  MATCH_CONFIRMED: 'MATCH_CONFIRMED',
  // 거래 관련
  DEAL_CREATED: 'DEAL_CREATED',
  DEAL_SUBMITTED: 'DEAL_SUBMITTED',
  DEAL_CONFIRMED: 'DEAL_CONFIRMED',
  DEAL_CANCELLED: 'DEAL_CANCELLED',
  // 정산/자원 관련
  SETTLEMENT_CALCULATED: 'SETTLEMENT_CALCULATED',
  RESOURCE_ALLOCATED: 'RESOURCE_ALLOCATED',
  RESOURCE_RELEASED: 'RESOURCE_RELEASED',
} as const

export type EvtSignatureKey = keyof typeof EVT_SIGNATURES
export type EvtSignatureValue = typeof EVT_SIGNATURES[EvtSignatureKey]
